# Generated by Django 4.0.5 on 2022-07-03 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('demo_link', models.CharField(blank=True, max_length=50, null=True)),
                ('source_link', models.CharField(blank=True, max_length=50, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.UUID('15abe248-4ca2-442c-bb48-080355601795'), primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
