# Generated by Django 4.0.5 on 2022-07-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_alter_projects_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
