# Generated by Django 4.0.5 on 2022-07-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_review_tag_delete_amir_delete_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
