# Generated by Django 4.0.5 on 2022-07-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_projects_vote_ratio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
